services:
  app:
    build: .
    container_name: my_amort
    command: python main.py --host 0.0.0.0 --port 8050 --reload reload-include *
    ports:
      - 8050:8050
    volumes:
      - .:/app

# docker-compose up --build